### List All Users
GET {{baseUrl}}/api/users
Authorization: Bearer {{headers.Authorization}}
Content-Type: application/json

### Get a User by ID
GET {{baseUrl}}/api/users/4
Authorization: Bearer {{headers.Authorization}}
Content-Type: application/json

### Edit a User
PUT {{baseUrl}}/api/users/4
Authorization: Bearer {{headers.Authorization}}
Content-Type: application/json

{
  "firstName": "Johny",
  "lastName": "Doe",
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "password123",
  "rolesId": [2, 3, 4]
}

### Delete a User
DELETE {{baseUrl}}/api/users/1
Authorization: Bearer {{headers.Authorization}}
Content-Type: application/json

### Inserting a User
POST {{baseUrl}}/api/users
Authorization: Bearer {{headers.Authorization}}
Content-Type: application/json

{
  "firstName": "Johny",
  "lastName": "Doe",
  "username": "johndoe",
  "email": "johndoe@example.com",
  "password": "password123",
  "rolesId": [2, 3, 4]
}