name: Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: riki
          POSTGRES_PASSWORD: riki@123
          POSTGRES_DB: dental_gp_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U riki"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Dependencies and Run Tests
        run: mvn clean test -Dspring.profiles.active=test

      - name: Generate Surefire HTML Report
        run: mvn surefire-report:report

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: surefire-html-report
          path: target/reports/surefire.html

